# Generated by Django 5.2.6 on 2026-02-14 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTCProfile',
            fields=[
                ('status', models.CharField(choices=[('INTERNAL', 'Internal Feed Only'), ('PUBLIC', 'Public News & Highlights'), ('PENDING', 'Pending')], default='PENDING', help_text='PENDING: Hec yerde gorunmur. INTERNAL: Login olanlar. PUBLIC: Hər kəs.', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Full Official Name')),
                ('slug', models.SlugField(blank=True, help_text='Avtomatik olaraq addan yaranır', unique=True)),
                ('host_country', models.CharField(max_length=100, verbose_name='Host Country')),
                ('address', models.TextField(verbose_name='Full Postal Address')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Official Website')),
                ('coordinates', models.CharField(blank=True, help_text='Format: Latitude, Longitude', max_length=255, null=True, verbose_name='Coordinates')),
                ('director_name', models.CharField(max_length=255, verbose_name='Director Name')),
                ('director_email', models.EmailField(max_length=254, verbose_name='Director Email')),
                ('director_bio', models.TextField(blank=True, null=True, verbose_name='Director Bio')),
                ('contact_person_name', models.CharField(max_length=255, verbose_name='Contact Person Name')),
                ('contact_person_email', models.EmailField(max_length=254, verbose_name='Contact Person Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Primary Phone Number')),
                ('establishment_year', models.PositiveIntegerField(verbose_name='Year of Establishment')),
                ('mission_statement', models.TextField(verbose_name='Mission & Vision Statement')),
                ('overview_text', models.TextField(verbose_name='Brief History/Overview')),
                ('specialization_areas', models.TextField(help_text='Key training focus areas e.g., enforcement, valuation', verbose_name='Areas of Specialization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='rtc_members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rtc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RTC Profile',
                'verbose_name_plural': 'RTC Profiles',
            },
        ),
        migrations.CreateModel(
            name='RTCEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERNAL', 'Internal Feed Only'), ('PUBLIC', 'Public News & Highlights'), ('PENDING', 'Pending')], default='PENDING', help_text='PENDING: Hec yerde gorunmur. INTERNAL: Login olanlar. PUBLIC: Hər kəs.', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='Results/Participant info for past events', verbose_name='Summary/Outcomes')),
                ('participant_count', models.PositiveIntegerField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, help_text='Attach report PDF', null=True, upload_to='event_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.rtcprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERNAL', 'Internal Feed Only'), ('PUBLIC', 'Public News & Highlights'), ('PENDING', 'Pending')], default='PENDING', help_text='PENDING: Hec yerde gorunmur. INTERNAL: Login olanlar. PUBLIC: Hər kəs.', max_length=20)),
                ('image', models.ImageField(upload_to='rtc_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='dashboard.rtcprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RTCProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERNAL', 'Internal Feed Only'), ('PUBLIC', 'Public News & Highlights'), ('PENDING', 'Pending')], default='PENDING', help_text='PENDING: Hec yerde gorunmur. INTERNAL: Login olanlar. PUBLIC: Hər kəs.', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Overview')),
                ('timeframe', models.CharField(help_text='e.g., 2024-2026', max_length=100)),
                ('partners', models.CharField(help_text='Partners Involved', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='dashboard.rtcprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RTCResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERNAL', 'Internal Feed Only'), ('PUBLIC', 'Public News & Highlights'), ('PENDING', 'Pending')], default='PENDING', help_text='PENDING: Hec yerde gorunmur. INTERNAL: Login olanlar. PUBLIC: Hər kəs.', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('TOR', 'Mandate / Terms of Reference'), ('MOU', 'Founding Memorandum'), ('STRATEGY', 'Strategic Plan'), ('PLAN', 'Annual Training Plan'), ('CATALOGUE', 'Training Catalogue'), ('REPORT', 'Annual Report / Newsletter'), ('PUB', 'Publication / Handbook'), ('ELEARN', 'E-Learning Link')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='rtc_docs/', verbose_name='PDF File')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='External Link (if applicable)')),
                ('description', models.TextField(blank=True, verbose_name='Short Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='dashboard.rtcprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
