# Generated by Django 5.2.6 on 2026-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtcprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='rtc_logos/', verbose_name='School Logo'),
        ),
    ]
