# Generated by Django 5.2.6 on 2026-02-14 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rtcprofile_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtcprofile',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='rtc_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
