# Generated by Django 5.2.6 on 2026-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_rtcprofile_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rtcevent',
            options={'ordering': ['-event_date']},
        ),
        migrations.RemoveField(
            model_name='rtcevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rtcevent',
            name='start_date',
        ),
        migrations.AddField(
            model_name='rtcevent',
            name='event_date',
            field=models.DateField(default='2024-01-01', verbose_name='Event Date'),
            preserve_default=False,
        ),
    ]
