# Generated by Django 5.2.6 on 2026-02-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_rtcevent_options_remove_rtcevent_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INTERNAL', 'Internal Feed Only'), ('PUBLIC', 'Public News & Highlights'), ('PENDING', 'Pending')], default='PENDING', help_text='PENDING: Hec yerde gorunmur. INTERNAL: Login olanlar. PUBLIC: Hər kəs.', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rtc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='dashboard.rtcprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
