/** Google Translate included languages — shared labels for custom select */
export const GT_LANG_CODES = [
  'en', 'ru', 'az', 'fr', 'de', 'es', 'it', 'tr', 'uk', 'pl', 'ro', 'ka', 'kk', 'uz', 'tg', 'hy',
  'be', 'bs', 'sq', 'mk', 'sr', 'hr', 'bg', 'lt', 'lv', 'et', 'fi', 'sv', 'no', 'da', 'nl', 'cs',
  'sk', 'sl', 'hu', 'el', 'he', 'pt', 'mt', 'is', 'me', 'md', 'ky',
];

export const GT_LANG_LABELS = {
  en: 'English',
  ru: 'Русский',
  az: 'Azərbaycan',
  fr: 'Français',
  de: 'Deutsch',
  es: 'Español',
  it: 'Italiano',
  tr: 'Türkçe',
  uk: 'Українська',
  pl: 'Polski',
  ro: 'Română',
  ka: 'ქართული',
  kk: 'Қазақ',
  uz: 'Oʻzbek',
  tg: 'Тоҷикӣ',
  hy: 'Հայերեն',
  be: 'Беларуская',
  bs: 'Bosanski',
  sq: 'Shqip',
  mk: 'Македонски',
  sr: 'Српски',
  hr: 'Hrvatski',
  bg: 'Български',
  lt: 'Lietuvių',
  lv: 'Latviešu',
  et: 'Eesti',
  fi: 'Suomi',
  sv: 'Svenska',
  no: 'Norsk',
  da: 'Dansk',
  nl: 'Nederlands',
  cs: 'Čeština',
  sk: 'Slovenčina',
  sl: 'Slovenščina',
  hu: 'Magyar',
  el: 'Ελληνικά',
  he: 'עברית',
  pt: 'Português',
  mt: 'Malti',
  is: 'Íslenska',
  me: 'Crnogorski',
  md: 'Moldovenească',
  ky: 'Кыргызча',
};

export const GT_LANGS_CSV = GT_LANG_CODES.join(',');
