# Generated by Django 5.2.6 on 2026-02-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_news'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtcpost',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='rtcpost',
            name='rtc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.rtcprofile'),
        ),
    ]
